2020-06-11 11:23:28,054 INFO: Microblog startup [in E:\AirConditionerSystem\microblog\app\__init__.py:38]
2020-06-11 11:28:36,854 INFO: Microblog startup [in E:\AirConditionerSystem\microblog\app\__init__.py:38]
2020-06-11 12:08:51,079 INFO: Microblog startup [in E:\AirConditionerSystem\microblog\app\__init__.py:40]
2020-06-11 12:09:00,848 ERROR: Exception on / [GET] [in e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\AirConditionerSystem\microblog\app\routes.py", line 43, in index
    return render_template('index.html', title='Home', posts = posts)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\AirConditionerSystem\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\AirConditionerSystem\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "E:\AirConditionerSystem\microblog\app\templates\base.html", line 22, in block "navbar"
    <li><a href="{{ url_for('explore') }}">Explore</a></li>
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "e:\airconditionersystem\microblog\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2020-06-11 12:11:01,520 INFO: Microblog startup [in E:\AirConditionerSystem\microblog\app\__init__.py:40]
2020-06-11 12:11:16,025 ERROR: Exception on /login [GET] [in e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\AirConditionerSystem\microblog\app\routes.py", line 70, in login
    return render_template('login.html', title='Sign In', form=form)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "e:\airconditionersystem\microblog\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\AirConditionerSystem\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\AirConditionerSystem\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\AirConditionerSystem\microblog\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\AirConditionerSystem\microblog\app\templates\login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\airconditionersystem\microblog\env\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "e:\airconditionersystem\microblog\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
